GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/MostrarEncargado.razor
cambios en la tabla de actualizar para que no se refresque de un solo el atributo sin envierlo a la base de datos
=> cambios necearios

GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/EntidadesAD/UnidadAD.cs, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/CrearUnidad.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Controlador/UnidadControlador.cs, GestionAsistentes.BlazorUI/GestionAsistentes.ReglasNegocio/UnidadRN.cs
=> finaliza unidad

GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/Contexto/GestionAsistenteContexto.cs, GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/Migrations/20241016015746_InitDB.Designer.cs, GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/Migrations/20241016015746_InitDB.cs, GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/Modelos/AsistenteEF.cs, GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/Modelos/BadgeEF.cs, GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/Modelos/EncargadoEF.cs, GestionAsistentes.BlazorUI/GestionAsistentes.Entidades/Asistente.cs, GestionAsistentes.BlazorUI/GestionAsistentes.Entidades/Badge.cs, GestionAsistentes.BlazorUI/GestionAsistentes.Entidades/Encargado.cs
unir los cambios para la entrega
=> cambios en la base de datos

GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/EntidadesAD/EstacionTrabajoAD.cs, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/MostrarAsistentes.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Controlador/EstacionTrabajoControlador.cs, GestionAsistentes.BlazorUI/GestionAsistentes.ReglasNegocio/EstacionTrabajoRN.cs
=> cambios en el horario

GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/EntidadesAD/BadgeAD.cs, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Layout/LayoutPrincipal.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/CrearBadge.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/MostrarBadge.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Controlador/BadgeControlador.cs, GestionAsistentes.BlazorUI/GestionAsistentes.ReglasNegocio/BadgeRN.cs
=> Agregar Badge

GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/MostrarHorario.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Controlador/HorarioControlador.cs
cambia visualizacion de la tarjeta en acordeones.
=> feature horario accordeon

GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/EntidadesAD/HistorialAccionesAD.cs, GestionAsistentes.BlazorUI/GestionAsistentes.AccesoDatos/EntidadesAD/UnidadAD.cs, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/CrearUnidad.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Components/Pages/Historial.razor, GestionAsistentes.BlazorUI/GestionAsistentes.BlazorUI/Controlador/HistorialAccionesControlador.cs, GestionAsistentes.BlazorUI/GestionAsistentes.Entidades/HistorialAcciones.cs, GestionAsistentes.BlazorUI/GestionAsistentes.ReglasNegocio/HistorialAccionesRN.cs
=> HistorialAcciones

GestionAsistente/GestionAsistente.BlazorUI/Components/Layout/LayoutPrincipal.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearAsistente.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearBadge.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearOficina.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearUnidad.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearUsuario.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/Historial.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarAsistentes.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarBadge.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarOficinas.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarReportes.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarUsuarios.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/EncargadoControlador.cs
=> Historial, paginación

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/EncargadoControlador.cs
cambios en condiciones para que e usuario tenga la inforamcion correcta y no pueda incorporar datos inconsistentes
=> cambios para que el usuario tenga la vista adeacuda

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/HorarioAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarHorario.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/HorarioControlador.cs, GestionAsistente/GestionAsistente.ReglasNegocio/HorarioRN.cs
se incorporo la funcion de eliminar todos los horarios asignados a la oficina, y la confirmaicon de eliminar para evitar a eliminacion por error
=> feature confirma eliminacion

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/EstacionTrabajoAD.cs, GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/OficinaAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearOficina.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarOficinas.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/OficinaControlador.cs, GestionAsistente/GestionAsistente.ReglasNegocio/OficinaRN.cs
Correcciones en Oficina y Encargado
=> Correcciones en Oficina y Encargado

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/EncargadoAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/EncargadoControlador.cs, GestionAsistente/GestionAsistente.ReglasNegocio/EncargadoRN.cs
la falta de validaciones asi como el tema del gesto de historial arreglado
=> featrure condiciones arregladas

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.ReglasNegocio/EncargadoRN.cs
comprobacion de cambios en el actualizar encargado
=> feature actualizar enargado

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarHorario.razor
cambios en los botones, seguir
=> feature cambios

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarHorario.razor
Cambios esteticos en como se en el apartado estetico, aun queda por mejorar, y la confiramcion de limpia de los horarios
=> deature cambios horario

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/BadgeAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearAsistente.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearOficina.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarBadge.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarOficinas.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/BadgeControlador.cs, GestionAsistente/GestionAsistente.BlazorUI/wwwroot/estilos/EstiloGeneral.css, GestionAsistente/GestionAsistente.ReglasNegocio/BadgeRN.cs
Cambios en CSS Crear Asistente y Busqueda por Unidad en Badge
=> Cambios en CSS Crear Asistente y Busqueda por Unidad en Badge

GestionAsistente/GestionAsistente.ReglasNegocio/EncargadoRN.cs
validaciones en los parametros permitidos por los campos de encargado
=> featrure validacciones encargado

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/EncargadoControlador.cs
=> paginación encargado resuelta

GestionAsistente/GestionAsistente.ReglasNegocio/EncargadoRN.cs
Correcciones en el mensaje de los errores y algunos errores menores
=> feature correccion validaciones

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor
=> featrue/ quitar comentarios

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/AsistenteAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarAsistentes.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/AsistenteControlador.cs, GestionAsistente/GestionAsistente.ReglasNegocio/AsistenteRN.cs
=> paginación asistente

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/HistorialAccionesAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearUnidad.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/Historial.razor, GestionAsistente/GestionAsistente.BlazorUI/Controlador/HistorialAccionesControlador.cs, GestionAsistente/GestionAsistente.BlazorUI/Controlador/UnidadControlador.cs, GestionAsistente/GestionAsistente.ReglasNegocio/HistorialAccionesRN.cs, GestionAsistente/GestionAsistente.ReglasNegocio/UnidadRN.cs
solución filtros de búsqueda y modales de unidad
=> unidad e historial

GestionAsistente/GestionAsistente.BlazorUI/Components/Layout/LayoutPrincipal.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/Ayuda.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarAsistentes.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarBadge.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarHorario.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarOficinas.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarReportes.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarUnidades.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarUsuarios.razor, GestionAsistente/GestionAsistente.BlazorUI/wwwroot/estilos/EstiloGeneral.css
Margenes de Ayuda y botones de paginacion
=> Margenes de Ayuda y botones de paginacion

GestionAsistente/GestionAsistente.AccesoDatos/EntidadesAD/BadgeAD.cs, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarBadge.razor, GestionAsistente/GestionAsistente.BlazorUI/wwwroot/estilos/EstiloGeneral.css
cambios en el tema de desactivar que se desactive el enlaze con el asistente
=> featrue cambios en badge

GestionAsistente/GestionAsistente.BlazorUI/Components/Account/Pages/Login.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/Login.razor
=> Validaciones y estilo login

GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearAsistente.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearBadge.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearOficina.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearUnidad.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/CrearUsuario.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/Historial.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarEncargado.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarOficinas.razor, GestionAsistente/GestionAsistente.BlazorUI/Components/Pages/MostrarReportes.razor, GestionAsistente/GestionAsistente.BlazorUI/wwwroot/estilos/EstiloGeneral.css
=> CSS y estilo general
